#Initialize Journal Environment variables, (file directories)
source /home/ezra/Journal/BackEnd/BashScripts/InitializeEnvVars.sh
#Journal aliases
alias NewEntry="~/Journal/BackEnd/BashScripts/NewEntry.sh"
alias Compile="~/Journal/BackEnd/BashScripts/FullCompileScript.sh"
alias Save="~/Journal/BackEnd/BashScripts/Save.sh"
alias TestEntry="~/Journal/BackEnd/BashScripts/TestEntry.sh"

#Navigation aliases
alias tojrnl="cd ${JournalDriveDir}"
alias vimrc="cd ~/GithubDrive/vimrc/"
alias liconf="cd ~/GithubDrive/linuxconfig/"
alias tojrnldev="cd ~/Journal/BackEnd/"
alias tojrnlsh="cd ~/Journal/BackEnd/BashScripts/"
